### ISSUE TITLE
If I modify "Public_Url" in appsettings.json and if it contains '-' char then it is not read properly in the code

### ISSUE THREAD

**Issue by SadanandRanbhor** [GinoCanessa/fhir-candle#14]
If I modify "Public_Url" in appsettings.json and if it contains '-' char then it is not read properly in the code"https://fhir-candle.azurewebsites.net"

**Comment by GinoCanessa** [comment]
Thanks for the report.  The issue is fixed in the next release (later today).  I will close the issue once the build is published.  Cheers!

**Comment by GinoCanessa** [comment]
Tested in v2023.906.2247 and everything looks correct.  Please let me know if you run into anything else.
